name = "DESSEM2Julia"
uuid = "5b3a2f8f-9ef8-4a52-9f7b-2a6d29f86e1c"
authors = ["Pedro Bittencourt"]
version = "1.0.0"
license = "MIT"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Colors = "0.12"
Compose = "0.9"
GraphPlot = "0.6"
Graphs = "1.13"
JLD2 = "0.4, 0.5"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
